src/Entity/Ajout.php
<?php

namespace App\Entity;
use App\Repository\AjoutsRepository;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;


/**
 * @UniqueEntity(fields={"ProjectName"}, message="The ProjectName is already used by another user")
 */
#[ORM\Entity(repositoryClass: AjoutsRepository::class)]
class Ajout
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 180, unique: true)]
    private ?string $ProjectName = null;

    
    #[ORM\Column]
    private ?string $Objet = null;

    #[ORM\Column(length: 100)]
    private ?string $Description = null;
    #[ORM\Column(length: 100)]
    private ?string $Categorie = null;

    #[ORM\Column(length: 100)]
    private ?string $Impact = null;

    #[ORM\Column(length: 100)]
    private ?string $Version = null;

    #[ORM\Column(length: 100)]
    private ?string $Solution = null;

    #[ORM\Column(options:['default'=> 'CURRENT_TIMESTAMP'])]
    private ?\DateTimeImmutable $created_at = null;

    public function __construct()
    {
        $this->created_at = new \DateTimeImmutable();
    }


    public function getId(): ?int
    {
        return $this->id;
    }

    public function getProjectName(): ?string
    {
        return $this->ProjectName;
    }

    public function setProjectName(string $ProjectName): self
    {
        $this->ProjectName = $ProjectName;

        return $this;
    }

    public function getObjet(): string
    {
        return $this->Objet;
    }

    public function setObjet(string $Objet): self
    {
        $this->Objet = $Objet;

        return $this;
    }

    /**
     * @see UserInterface
     */
    public function eraseCredentials()
    {
        // If you store any temporary, sensitive data on the user, clear it here
        // $this->plainObjet = null;
    }

    public function getDescription(): ?string
    {
        return $this->Description;
    }
    

    public function setDescription(string $Description): self
    {
        $this->Description = $Description;

        return $this;
    }
    public function getCategorie(): ?string
    {
        return $this->Categorie;
    }
    public function setCategorie(string $Categorie): self
    {
        $this->Categorie = $Categorie;

        return $this;
    }
    public function getImpact(): ?string
    {
        return $this->Impact;
    }
    public function setImpact(string $Impact): self
    {
        $this->Impact = $Impact;

        return $this;
    }

    public function getVersion(): ?string
    {
        return $this->Version;
    }

    public function setVersion(string $Version): self
    {
        $this->Version = $Version;

        return $this;
    }

    public function getSolution(): ?string
    {
        return $this->Solution;
    }
    public function setSolution(string $Solution): self
    {
        $this->Solution = $Solution;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->created_at;
    }

    public function setCreatedAt(\DateTimeImmutable $created_at): self
    {
        $this->created_at = $created_at;

        return $this;
    }
}

src/Entity/Contact.php
<?php

namespace App\Entity;

use App\Entity\id;
use App\Repository\ContactRepository;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: ContactRepository::class)]
class Contact
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column(name: "id_mail", type: "integer")]
    private ?int $idMail = null;

    #[ORM\ManyToOne(targetEntity: Users::class)]
    #[ORM\JoinColumn(name: "user_id", referencedColumnName: "id", nullable: false)]
    private ?Users $user = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\NotBlank()]
    #[Assert\Length(min: 2, max: 50)]
    private ?string $Firstname = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\NotBlank()]
    #[Assert\Length(min: 2, max: 50)]
    private ?string $Lastname = null;

    #[ORM\Column(length: 255)]
    #[Assert\Email()]
    #[Assert\Length(min: 2, max: 180)]
    private ?string $email = null;

    #[ORM\Column(length: 255, nullable: true)]
    #[Assert\Length(min: 2, max: 180)]
    private ?string $subject = null;

    #[ORM\Column(type: Types::TEXT)]
    #[Assert\NotBlank()]
    private ?string $message = null;

    #[ORM\Column]
    #[Assert\NotNull()]
    private ?\DateTimeImmutable $createdAt;

    public function __construct()
    {
        $this->createdAt = new \DateTimeImmutable();
    }
    public function getIdMail(): ?int
    {
        return $this->idMail;
    }
    public function getUser(): ?Users
    {
        return $this->user;
    }

    public function setUser(Users $user): self
    {
        $this->user = $user;

        return $this;
    }
    public function getFirstname(): ?string
    {
        return $this->Firstname;
    }

    public function setFirstname(?string $Firstname): self
    {
        $this->Firstname = $Firstname;

        return $this;
    }

    public function getLastname(): ?string
    {
        return $this->Lastname;
    }

    public function setLastname(?string $Lastname): self
    {
        $this->Lastname = $Lastname;

        return $this;
    }

    public function getEmail(): ?string
    {
        return $this->email;
    }

    public function setEmail(string $email): self
    {
        $this->email = $email;

        return $this;
    }

    public function getSubject(): ?string
    {
        return $this->subject;
    }

    public function setSubject(?string $subject): self
    {
        $this->subject = $subject;

        return $this;
    }

    public function getMessage(): ?string
    {
        return $this->message;
    }

    public function setMessage(string $message): self
    {
        $this->message = $message;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }
}

src/Controller/DefaultController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class DefaultController extends AbstractController
{
    #[Route('/', name: 'app_default')]
    public function index(): Response
    {
        return $this->render('default/accueil.html.twig');
    }
}

src/src/Controller/DefaultController.php
<?php

namespace App\Controller;

use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;
use App\Entity\Users;

class DefaultController extends AbstractController
{
    #[Route('/', name: 'app_default')]
    public function index(): Response
    {
        return $this->render('default/accueil.html.twig');
    }
}

templates/default/accueil.html.twig
{% extends 'base.html.twig' %}

{% block body %}

	<title>Page d'accueil</title>

	<!-- Page content-->

	<div class="bg_form">
		<h1 class="title_form">HANOVER</h1>
		<div class="row d-flex justify-content-center">
			<div class="col-sm-4">
				<div class="card">
					<div class="card-body">
						<h5 class="card-title">Ajouter</h5>
						<p class="card-text">Ici vous pouvez ajouter les solutions à des bug rencontrés.</p>
						<a href="ajouter" class="btn btn-outline-danger btn-lg">Cliquez ici !</a>
					</div>
				</div>
			</div>
			<div class="col-sm-4">
				<div class="card">
					<div class="card-body">
						<h5 class="card-title">Questions</h5>
						<p class="card-text">Ici vous avez accès à tout les bugs rencontrés par nos collaborateurs.</p>
						<a href="questions" class="btn btn-outline-danger btn-lg">Cliquez ici !</a>
					</div>
				</div>
			</div>
		</div>
		<br>
        <br>
		<div class="row d-flex justify-content-center">
			<div class="col-sm-4">
				<div class="card">
					<div class="card-body">
						<h5 class="card-title">Modification</h5>
						<p class="card-text">Ici vous avez la possibilité de modifier les informations d'un ticket.</p>
						<a href="pre-modification" class="btn btn-outline-danger btn-lg">Cliquez ici !</a>
					</div>
				</div>
			</div>
			<div class="col-sm-4">
				<div class="card">
					<div class="card-body">
						<h5 class="card-title">Contact</h5>
						<p class="card-text">Ici vous pouvez contacter un administrateur si vous avez des questions.</p>
						<a href="contact" class="btn btn-outline-danger btn-lg">Cliquez ici !</a>
					</div>
				</div>
			</div>
		</div>
		<br>
	</div>
	<!-- End page content -->
{% endblock %}

templates/default/ajout.html.twig
{% extends 'base.html.twig' %}

{% block body %}

<title>HanoverFAQ - Ajout</title>

<!-- Page content-->

<div class="bg_form">
<form  class="form_content">
    <h2 class="title_form" >Page d'ajout</h2>
    <h3 class="title_form">Quelle est la problématique à ajouter ?</h3>
    <br>
    <div class="form-group">
    <label for="NomProjet">Nom du projet</label>
    <input type="text" class="form-control" id="project" placeholder="Project">
    </div>
    <div class="form-group">
        <label for="Categories">Catégorie</label>
        <div class="form-group">
            <select class="form-control" id="exampleFormControlSelect1">
              <option>Application mobile</option>
              <option>Base de données</option>
              <option>Embarqué</option>
              <option>Général</option>
              <option>IHM</option>
              <option>Intervention sur les données</option>
              <option>Livraison / Mise à jour</option>
              <option>Serveur</option>
              <option>SIRI / SIRI Light</option>
              <option>Non déterminé</option>
            </select>
        </div>
        </div>
    <div class="form-group">
        <label for="Objet">Objet</label>
        <input type="text" class="form-control" id="project" placeholder="Summary">
        </div>
    <div class="form-group">
        <label for="Description">Description</label>
        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" placeholder="Description"></textarea>
        </div>
    <div class="form-group">
        <label for="Version">Version du logiciel</label>
        <input type="text" class="form-control" id="version" placeholder="Version">
    </div>
        <br>
    
    <div class="form-group">
    <label for="Solution">Solution : </label>
    <textarea class="form-control" id="Solution" rows="10"></textarea>
    <div class="mb-3">
        <label for="formFileMultiple" class="form-label">Ajouter des fichiers : </label>
        <input class="form-control" type="file" id="formFileMultiple" multiple>
        <button type="button" class="btn btn-success btn-rechercher">Rechercher</button>
    </div>
    <button type="submit" class="btn btn-primary">Envoyer</button>
</div>
</form>
</div>

<div class="bg_form">



</div>
<!-- End page content -->

<!-- a terme, btn pour switch de langue -->




<!-- Bootstrap core JS-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
<!-- Core theme JS-->
<script src="js/scripts.js"></script>
<!-- End bootstrap core JS -->

{% endblock %}

templates/default/ajouter.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	Create a new Project


{% endblock %}

{% block body %}
				<section class="container">
					<div class="row">
						<div class="col">
							<h1>
								Create a new project
							</h1>
							{{ form_start(ajoutForm) }}
							<fieldset>
								{{ form_row(ajoutForm.ProjectName) }}
								<br>
								{{ form_row(ajoutForm.Categorie) }}
								<br>
								{{ form_row(ajoutForm.Impact) }}
								<br>
								{{ form_row(ajoutForm.Objet) }}
								{{ form_row(ajoutForm.Version) }}
								{{ form_row(ajoutForm.Description) }}
								{{ form_row(ajoutForm.Solution) }}
							</fieldset>
							<button type="submit" class="btn btn-danger btn-lg mt-3">
								Create
							</button>
							{{ form_end(ajoutForm) }}
						</div>
					</div>
				</section>
	{% endblock %}

templates/default/contact.html.twig
{% extends 'base.html.twig' %}

{% block title %}
    Register
        
    
{% endblock %}

{% block body %}

    <section class="container">
        <div class="row">
            <div class="col">
                <h1>
                    Register       
                </h1>
                {{ form_start(contactForm) }}
                <fieldset>
                    {{ form_row(contactForm.email) }}
                    {{ form_row(contactForm.firstname) }}
                    {{ form_row(contactForm.lastname) }}
                    {{ form_row(contactForm.subject) }}
                    {{ form_row(contactForm.message) }}
                </fieldset>

                <button type="submit" class="btn btn-danger btn-lg mt-3">
                    Register         
                </button>
                {{ form_end(contactForm) }}
            </div>
        </div>
    </section>

{% endblock %}

templates/default/modification.html.twig
{% extends 'base.html.twig' %}

{% block title %}
	Modification
{% endblock %}

{% block body %}
<br>
	<section class="container">
		<div class="row">
			<div class="col">
				<h1>
					Modification
				</h1>
				<form method="post" action="{{ path('app_modification', {'id': ajout.id}) }}">
					{{ form_start(modifForm) }}
					<fieldset>
						{{ form_row(modifForm.ProjectName) }}
						<br>
						{{ form_row(modifForm.Categorie) }}
						<br>
						{{ form_row(modifForm.Impact) }}
						<br>
						{{ form_row(modifForm.Objet) }}
						{{ form_row(modifForm.Version) }}
						{{ form_row(modifForm.Description) }}
						{{ form_row(modifForm.Solution) }}
					</fieldset>
					<button type="submit" class="btn btn-danger btn-lg mt-3">
						Modifier
					</button>
					{{ form_end(modifForm) }}
				</form>
			</div>
		</div>
	</section>
</div></form></div>

{% endblock %}

templates/default/pre-modification.html.twig
{% extends 'base.html.twig' %}

{% block body %}

<title>HanoverFAQ - Modification</title>

        <!-- Page content-->
        
        <br><br>
        <h2 class="title_form">Liste des problématiques modifiables :</h2>
        <div class="bg_form">
            <li class="no_list">
                <ul class="no_list" id="mantis-list">
                    {% for pb in allProbs %}
                    <li><a class="dropdown-item">{{pb.projectName}}<button type="button" class="btn btn-danger" onclick="location.href='/modification/{{pb.id}}';">Modifier</button> </a></li>
                    <li><hr class="dropdown-divider" /></li>
                    {% endfor %}
                </ul>
            </li>
        </div>
        <!-- End page content -->

        <!-- ajouter une liste de séléction des problématiques avant -->



        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
        <!-- End bootstrap core JS -->

{% endblock %}

templates/default/questions.html.twig
{% extends 'base.html.twig' %}

{% block body %}

<link href="https://unpkg.com/@yaireo/tagify/dist/tagify.css" rel="stylesheet" type="text/css" />


<title>HanoverFAQ</title>

<!-- Page content-->

<div class="bg_form question-form" id="Q1">
<br>
<h2 class="title_form">Question 1 - Votre problème concerne...</h2>

<p class="questions-tree"></p>
<div class="zone-questions">
    <div class="row">
        <div class="col-sm btn-outline-primary case-question" onclick="R1_1()">
            <p class="question">Application mobile</p>
        </div>
        <div class="col-sm btn-outline-primary case-question" onclick="R1_2()">
            <p class="question">Base de données</p>
        </div>
        <div class="col-sm btn-outline-primary case-question" onclick="R1_3()">
            <p class="question">Embarqué</p>
        </div>
        <div class="col-sm btn-outline-primary case-question" onclick="R1_4()">
            <p class="question">Général</p>
        </div>
    </div>
        <div class="row">
            <div class="col-sm btn-outline-primary case-question" onclick="R1_5()">
            <p class="question">IHM</p>
            </div>
            <div class="col-sm btn-outline-primary case-question" onclick="R1_6()">
            <p class="question">Intervention sur les données</p>
            </div>
            <div class="col-sm btn-outline-primary case-question" onclick="R1_7()">
            <p class="question">Livraison / Mise à jour</p>
            </div>
            <div class="col-sm btn-outline-primary case-question" onclick="R1_8()">
            <p class="question">Serveur</p>
        </div>
    </div>
        <div class="row">
            <div class="col-sm btn-outline-primary case-question" onclick="R1_9()">
            <p class="question">SIRI / SIRI Light</p>
            </div>
            <div class="col-sm btn-outline-primary case-question" onclick="R1_10()">
            <p class="question">Non déterminé</p>
        </div>
    </div>
    <br>
</div>
<!-- <button type="button" class="btn btn-warning btn-rechercher">Rechercher</button> -->
</div>

<div class="bg_form question-form-invisible" id="Q2">
<br>
<h2 class="title_form">Question 2 - Son impact est-il...</h2>
<button type="button" class="btn btn-secondary questions-tree" onclick="Retour1()">Retour</button>
{# <p class="questions-tree" id="history1">/Catégorie</p> #}
<div class="container">
    <div class="row">
        <div class="col-sm btn-outline-primary case-question" onclick="R2_1()">
            <p class="question">Mineur</p>
        </div>
        <div class="col-sm btn-outline-primary case-question" onclick="R2_2()">
            <p class="question">Majeur</p>
        </div>
        <div class="col-sm btn-outline-primary case-question" onclick="R2_3()">
            <p class="question">Bloquant</p>
        </div>
        <div class="col-sm btn-outline-primary case-question" onclick="R2_4()">
            <p class="question">Simple</p>
        </div>
    </div>
        <div class="row">
            <div class="col-sm btn-outline-primary case-question" onclick="R2_5()">
            <p class="question">Critique</p>
            </div>
            <div class="col-sm btn-outline-primary case-question" onclick="R2_6()">
            <p class="question">Fonctionnalité</p>
            </div>
            <div class="col-sm btn-outline-primary case-question" onclick="R2_7()">
            <p class="question">Cosmétique</p>
            </div>
            <div class="col-sm btn-outline-primary case-question" onclick="R2_8()">
            <p class="question">Serveur</p>
        </div>
    </div>
        <div class="row">
            <div class="col-sm btn-outline-primary case-question" onclick="R2_9()">
            <p class="question">Je ne sais pas</p>
        </div>
    </div>
    <br>
</div>
<!-- <button type="button" class="btn btn-warning btn-rechercher">Rechercher</button> -->
</div>

<div class="bg_form question-form-invisible" id="Q3">
<br>
<h2 class="title_form">Question 3 - Ajouter des mots clés à la recherche :</h2>
<button type="button" class="btn btn-secondary questions-tree" onclick="Retour2()">Retour</button>
{# <p class="questions-tree" id="history1">/Catégorie</p>
<p class="questions-tree" id="history2">/Catégorie/Impact</p> #}
<div class="container">
    <br>

    <!-- https://larainfo.com/blogs/bootstrap-5-tags-input-examples -->
    
    <input name='tags' value='' class="form-control" autofocus>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap/5.1.0/js/bootstrap.min.js"></script>
    <script src="https://unpkg.com/@yaireo/tagify"></script>
    <script src="https://unpkg.com/@yaireo/tagify@3.1.0/dist/tagify.polyfills.min.js"></script>
    <script>

    var input = document.querySelector('input[name=tags]');
    var tagify = new Tagify(input);
    


    // définir une fonction pour afficher les valeurs de tous les tags
    function displayTags() {
        // récupérer la valeur de la barre de tags
        var tagValues = tagify.value;
        // afficher le tableau dans la console
        const valuesTags = tagValues.map(obj => obj.value);
        console.log(valuesTags);
        sessionStorage.setItem('ReqSQL3', valuesTags);
        document.cookie = 'ReqSQL3='+valuesTags;
    }

    </script>
    <br>
    
</div>
<button onclick="displayTags(); window.location='/resultat';" class="btn btn-success btn-rechercher">Rechercher</button>
</div>


<!-- End page content -->

    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="public\assets\js\scripts.js"></script>
    <!-- End bootstrap core JS -->





{% endblock %}

templates/default/resultat.html.twig
{% extends 'base.html.twig' %}

{% block body %}

{% set ReqSQL1 = app.request.cookies.get('ReqSQL1') %}
{% set ReqSQL2 = app.request.cookies.get('ReqSQL2') %}
{% set ReqSQL3 = app.request.cookies.get('ReqSQL3') %}
{% set tags = ReqSQL3|split(',') %}
{% set Array = [] %}

<title>HanoverFAQ</title>

        <!-- Page content-->
        
        <br><br>
        <h2 class="title_form">Liste des problématiques correspondant à la recherche</h2>
        
        <br>

        <div class="centraient">
            <button onclick="window.location='/resultat_mantis'" type="button" class="btn btn-primary">Voir les mantis</button>
        </div>

        <div class="bg_form">
            <li class="no_list">
                <ul class="no_list" id="mantis-list">
                    {% for rs in allResults %}
                        {% if rs.Categorie == ReqSQL1 %}
                            {% if rs.Impact == ReqSQL2 %}
                                {% for tag in tags %}
                                    {% if rs.description matches '/\\b' ~ tag ~ '/i' %}
                                        {% if rs.id not in Array %}
                                            <li><a class="dropdown-item">{{rs.projectName}}<button onclick="window.location='/modification/{{rs.id}}'" type="button" class="btn btn-primary">Voir la solution</button> </a></li>
                                            <li><hr class="dropdown-divider" /></li>
                                            {% set Array = Array|merge([rs.id]) %}
                                        {% endif %}
                                    {% endif %}
                                {% endfor %}
                            {% endif %}
                        {% endif %}
                    {% endfor %}
                    
                    
                </ul>
            </li>
        </div>
        <!-- End page content -->




        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        {# <script src="js/scripts.js"></script> #}
        <!-- End bootstrap core JS -->

{% endblock %}

templates/default/resultat_mantis.html.twig
{% extends 'base.html.twig' %}

{% block body %}

{% set ReqSQL1 = app.request.cookies.get('ReqSQL1') %}
{% set ReqSQL2 = app.request.cookies.get('ReqSQL2') %}
{% set ReqSQL3 = app.request.cookies.get('ReqSQL3') %}
{% set tags = ReqSQL3|split(',') %}
{% set Array = [] %}

<title>HanoverFAQ</title>

        <!-- Page content-->
        
        <br><br>
        <h2 class="title_form">Liste des mantis correspondant à la recherche</h2>

        <br>

        <div class="centraient">
            <button onclick="window.location='/resultat'" type="button" class="btn btn-primary">Retour aux problématiques</button>
        </div>

        <div class="bg_form">
            <li class="no_list">
                <ul class="no_list" id="mantis-list">
                    {% for rs in allResults %}
                        <li><a class="dropdown-item">{{rs.projectName}}<button onclick="#" type="button" class="btn btn-primary center">Voir le mantis</button> </a></li>
                        <li><hr class="dropdown-divider" /></li>
                    {% endfor %}
                </ul>
            </li>
        </div>
        <!-- End page content -->




        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        {# <script src="js/scripts.js"></script> #}
        <!-- End bootstrap core JS -->

{% endblock %}

templates/default/solution.html.twig
{% extends 'base.html.twig' %}

{% block body %}

        <!-- Page content-->
        
        <div class="bg_form">

            <div class="form-group">
                <label for="exampleFormControlTextarea1">Solution : </label>
                <textarea class="form-control" id="exampleFormControlTextarea1" rows="10"></textarea>
                <div class="mb-3">
                    <label for="formFileMultiple" class="form-label">Ajouter des fichiers : </label>
                    <input class="form-control" type="file" id="formFileMultiple" multiple>
                    <button type="button" class="btn btn-success btn-rechercher">Rechercher</button>
                </div>
            </div>

        </div>
        <!-- End page content -->


        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="js/scripts.js"></script>
        <!-- End bootstrap core JS -->

{% endblock %}